# pdf_export.py
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether
)
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor
from io import BytesIO
from datetime import datetime


# Brand colors (matching your UI)
BRAND_PURPLE = HexColor('#8b6cff')
BRAND_PURPLE_DARK = HexColor('#6e52e8')
BRAND_GREEN = HexColor('#39dca4')
BRAND_YELLOW = HexColor('#f3bd55')
BRAND_RED = HexColor('#ff6575')
BRAND_BLUE = HexColor('#74b9ff')
DARK_BG = HexColor('#10151e')
DARK_BG_2 = HexColor('#080b10')
TEXT_LIGHT = HexColor('#f5f7fb')
TEXT_DIM = HexColor('#a3adbd')
TEXT_MUTED = HexColor('#697485')
BORDER = HexColor('#2a3040')


class AuditPDF:
    def __init__(self, audit):
        self.audit = audit
        self.buffer = BytesIO()
        self.styles = getSampleStyleSheet()
        self._setup_styles()

    def _setup_styles(self):
        """Custom paragraph styles"""
        self.styles.add(ParagraphStyle(
            name='BrandTitle',
            fontName='Helvetica-Bold',
            fontSize=22,
            textColor=BRAND_PURPLE,
            spaceAfter=4
        ))
        self.styles.add(ParagraphStyle(
            name='SectionTitle',
            fontName='Helvetica-Bold',
            fontSize=14,
            textColor=HexColor('#111111'),
            spaceBefore=16,
            spaceAfter=8
        ))
        self.styles.add(ParagraphStyle(
            name='MetaText',
            fontName='Helvetica',
            fontSize=10,
            textColor=HexColor('#555555'),
            spaceAfter=2
        ))
        self.styles.add(ParagraphStyle(
            name='BodyText2',
            fontName='Helvetica',
            fontSize=10,
            textColor=HexColor('#222222'),
            leading=14,
            spaceAfter=6
        ))
        self.styles.add(ParagraphStyle(
            name='CodeText',
            fontName='Courier',
            fontSize=9,
            textColor=HexColor('#1a1a1a'),
            leading=12,
            leftIndent=8,
            spaceAfter=4
        ))
        self.styles.add(ParagraphStyle(
            name='FindingTitle',
            fontName='Helvetica-Bold',
            fontSize=11,
            textColor=HexColor('#111111'),
            spaceAfter=4
        ))
        self.styles.add(ParagraphStyle(
            name='SmallText',
            fontName='Helvetica',
            fontSize=8,
            textColor=HexColor('#777777'),
            leading=11
        ))

    def _sev_color(self, severity):
        return {
            'HIGH': BRAND_RED,
            'MEDIUM': BRAND_YELLOW,
            'LOW': BRAND_BLUE,
        }.get(severity, TEXT_MUTED)

    def _score_color(self, score):
        if score >= 80:
            return BRAND_GREEN
        elif score >= 50:
            return BRAND_YELLOW
        return BRAND_RED

    def _draw_cover(self, canv, doc):
        """Cover page background"""
        canv.saveState()
        canv.setFillColor(DARK_BG)
        canv.rect(0, 0, LETTER[0], LETTER[1], fill=True, stroke=False)
        canv.setFillColor(DARK_BG_2)
        canv.rect(0, 0, LETTER[0], LETTER[1] * 0.5, fill=True, stroke=False)
        # Purple accent bar
        canv.setFillColor(BRAND_PURPLE)
        canv.rect(0, LETTER[1] - 6, LETTER[0], 6, fill=True, stroke=False)
        canv.restoreState()

    def _draw_header_footer(self, canv, doc):
        """Header + footer on every page"""
        canv.saveState()
        # Header line
        canv.setStrokeColor(BORDER)
        canv.setLineWidth(0.5)
        canv.line(40, LETTER[1] - 40, LETTER[0] - 40, LETTER[1] - 40)
        # Header text
        canv.setFont('Helvetica-Bold', 9)
        canv.setFillColor(BRAND_PURPLE)
        canv.drawString(40, LETTER[1] - 32, 'SECUREAUDIT')
        canv.setFont('Helvetica', 8)
        canv.setFillColor(TEXT_MUTED)
        canv.drawRightString(
            LETTER[0] - 40, LETTER[1] - 32,
            'Compliance Report'
        )
        # Footer
        canv.setStrokeColor(BORDER)
        canv.line(40, 40, LETTER[0] - 40, 40)
        canv.setFont('Helvetica', 8)
        canv.setFillColor(TEXT_MUTED)
        canv.drawString(40, 28, 'Generated by SecureAudit — AI-Powered Network Compliance Auditor')
        canv.drawRightString(LETTER[0] - 40, 28, 'Page %d' % doc.page)
        canv.restoreState()

    def _cover_page(self):
        """Title page"""
        story = []
        story.append(Spacer(1, 1.5 * inch))
        story.append(Paragraph(
            '<font color="#a996ff" size="11">NETWORK SECURITY AUDIT</font>',
            self.styles['BodyText2']
        ))
        story.append(Spacer(1, 12))
        story.append(Paragraph(
            '<font color="#ffffff" size="34" face="Helvetica-Bold">Compliance Report</font>',
            self.styles['BodyText2']
        ))
        story.append(Spacer(1, 6))
        story.append(Paragraph(
            '<font color="#a3adbd" size="12">AI-Driven Multi-Vendor Analysis</font>',
            self.styles['BodyText2']
        ))
        story.append(Spacer(1, 2.5 * inch))
        
        # Metadata block
        meta_data = [
            ['Device / File:', self.audit.get('filename', 'unknown')],
            ['Vendor:', self.audit.get('vendor', 'unknown')],
            ['Scan Date:', self.audit.get('timestamp', '')],
            ['Compliance Score:', str(self.audit.get('compliance_score', 0)) + '%'],
            ['Total Rules:', str(self.audit.get('total_rules', 0))],
            ['Violations:', str(self.audit.get('violation_count', 0))],
        ]
        meta_table = Table(meta_data, colWidths=[1.8 * inch, 4.5 * inch])
        meta_table.setStyle(TableStyle([
            ('FONT', (0, 0), (0, -1), 'Helvetica-Bold', 10),
            ('FONT', (1, 0), (1, -1), 'Helvetica', 10),
            ('TEXTCOLOR', (0, 0), (0, -1), HexColor('#a996ff')),
            ('TEXTCOLOR', (1, 0), (1, -1), HexColor('#ffffff')),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 1.5 * inch))
        story.append(Paragraph(
            '<font color="#697485" size="8">This report was generated automatically by SecureAudit. '
            'All findings are traceable to specific config lines and mapped to NIST SP 800-53 and CIS Benchmarks.</font>',
            self.styles['BodyText2']
        ))
        story.append(PageBreak())
        return story

    def _summary_section(self):
        """Overview + score"""
        story = []
        story.append(Paragraph('Executive Summary', self.styles['SectionTitle']))
        
        a = self.audit
        score = a.get('compliance_score', 0)
        passed = a.get('passed_count', 0)
        violations = a.get('violation_count', 0)
        total = a.get('total_rules', 0)
        vendor = a.get('vendor', 'UNKNOWN')

        # Verdict
        if score >= 80:
            verdict = 'EXCELLENT'
            verdict_color = '#22a97c'
        elif score >= 50:
            verdict = 'NEEDS WORK'
            verdict_color = '#d99b1f'
        else:
            verdict = 'CRITICAL'
            verdict_color = '#e5394f'

        summary_html = (
            '<font color="#555555" size="10">'
            'This device config was analyzed against ' + str(total) + ' security rules. '
            '<b>' + str(passed) + '</b> rules passed and <b>' + str(violations) + '</b> were flagged as violations. '
            'The device is running <b>' + vendor + '</b> software.'
            '</font>'
        )
        story.append(Paragraph(summary_html, self.styles['BodyText2']))
        story.append(Spacer(1, 14))

        # Stat cards table
        stat_data = [
            [
                Paragraph('<font color="' + verdict_color + '" size="24"><b>' + str(score) + '%</b></font><br/><font color="#777777" size="8">COMPLIANCE SCORE</font>', self.styles['BodyText2']),
                Paragraph('<font color="#22a97c" size="24"><b>' + str(passed) + '</b></font><br/><font color="#777777" size="8">PASSED</font>', self.styles['BodyText2']),
                Paragraph('<font color="#e5394f" size="24"><b>' + str(violations) + '</b></font><br/><font color="#777777" size="8">VIOLATIONS</font>', self.styles['BodyText2']),
                Paragraph('<font color="#8b6cff" size="24"><b>' + verdict + '</b></font><br/><font color="#777777" size="8">VERDICT</font>', self.styles['BodyText2']),
            ]
        ]
        stat_table = Table(stat_data, colWidths=[1.6 * inch] * 4)
        stat_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), HexColor('#f8f9fb')),
            ('BOX', (0, 0), (-1, -1), 0.5, BORDER),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, BORDER),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('TOPPADDING', (0, 0), (-1, -1), 14),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 14),
        ]))
        story.append(stat_table)
        story.append(Spacer(1, 6))
        return story

    def _violations_section(self):
        """Full list of violations"""
        story = []
        violations = self.audit.get('violations', [])
        
        story.append(Paragraph('Security Findings — Detailed Report', self.styles['SectionTitle']))
        story.append(Paragraph(
            '<font color="#777777" size="9">' + str(len(violations)) + ' violations found. '
            'Each finding includes the recommended fix and a full AI-generated explanation.</font>',
            self.styles['BodyText2']
        ))
        story.append(Spacer(1, 12))

        if not violations:
            story.append(Paragraph(
                '<font color="#22a97c" size="12"><b>✓ No violations found — this config is compliant!</b></font>',
                self.styles['BodyText2']
            ))
            return story

        # Sort by severity (HIGH first)
        order = {'HIGH': 0, 'MEDIUM': 1, 'LOW': 2}
        sorted_v = sorted(violations, key=lambda v: order.get(v.get('severity', 'LOW'), 3))

        for i, v in enumerate(sorted_v, 1):
            sev = v.get('severity', 'UNKNOWN')
            sev_color = self._sev_color(sev)
            desc = v.get('description', 'No description')
            rule = v.get('rule', 'unknown')
            rem = v.get('remediation', 'N/A')
            nist = v.get('nist_control', '')
            cis = v.get('cis_benchmark', '')
            line_num = v.get('line_number')
            line_content = v.get('line_content', '')
            ai = v.get('ai_explanation', '')

            # Build finding block
            block = []
            # Title with severity
            hex_sev = '#%02x%02x%02x' % (
                int(sev_color.red * 255),
                int(sev_color.green * 255),
                int(sev_color.blue * 255)
            )
            title_html = (
                '<font color="' + hex_sev + '" size="9"><b>[' + sev + ']</b></font>  '
                '<font color="#111111" size="11"><b>' + str(i) + '. ' + desc + '</b></font>'
            )
            block.append(Paragraph(title_html, self.styles['FindingTitle']))

            # Rule + compliance badges
            badges = ['Rule: <b>' + rule + '</b>']
            if nist:
                badges.append('NIST: ' + nist)
            if cis:
                badges.append('CIS: ' + cis)
            block.append(Paragraph(
                '<font color="#777777" size="8">' + '  |  '.join(badges) + '</font>',
                self.styles['SmallText']
            ))
            block.append(Spacer(1, 6))

            # Config line trace
            if line_num:
                block.append(Paragraph(
                    '<font color="#666666" size="9"><b>Config Line ' + str(line_num) + ':</b> '
                    '<font face="Courier" color="#8b6cff">' + (line_content or 'configuration issue detected') + '</font></font>',
                    self.styles['BodyText2']
                ))

            # Recommended fix
            fix_html = (
                '<font color="#22a97c" size="9"><b>RECOMMENDED FIX</b></font><br/>'
                '<font face="Courier" size="9" color="#111111">' + rem.replace('<', '&lt;').replace('>', '&gt;').replace('\n', '<br/>') + '</font>'
            )
            block.append(Paragraph(fix_html, self.styles['BodyText2']))
            block.append(Spacer(1, 6))

            # AI explanation (strip markdown, convert to simple text)
            if ai:
                ai_clean = ai.replace('###', '').replace('**', '').replace('`', '')
                ai_lines = []
                for line in ai_clean.split('\n'):
                    line = line.strip()
                    if not line:
                        continue
                    # Escape HTML
                    line = line.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
                    if line.startswith('- '):
                        ai_lines.append('&nbsp;&nbsp;&nbsp;• ' + line[2:])
                    elif line and line[0].isdigit() and '. ' in line[:5]:
                        ai_lines.append('&nbsp;&nbsp;&nbsp;' + line)
                    elif line.isupper() or (line and line.endswith(':') and len(line) < 40):
                        ai_lines.append('<b>' + line + '</b>')
                    else:
                        ai_lines.append(line)

                ai_html = (
                    '<font color="#6e52e8" size="9"><b>AI EXPLANATION</b></font><br/>'
                    '<font color="#333333" size="9">' + '<br/>'.join(ai_lines) + '</font>'
                )
                block.append(Paragraph(ai_html, self.styles['BodyText2']))

            # Divider
            block.append(Spacer(1, 6))
            divider = Table([['']], colWidths=[6.5 * inch], rowHeights=[1])
            divider.setStyle(TableStyle([
                ('LINEBELOW', (0, 0), (-1, -1), 0.5, BORDER),
            ]))
            block.append(divider)
            block.append(Spacer(1, 12))

            story.append(KeepTogether(block))

        return story

    def _footer_section(self):
        """Closing note"""
        story = []
        story.append(Spacer(1, 20))
        story.append(Paragraph(
            '<font color="#697485" size="8">'
            'This report was generated by SecureAudit. All findings are traceable to specific '
            'configuration lines. Remediation commands are vendor-specific and tested against '
            'industry best practices for Cisco IOS, Juniper Junos, Arista EOS, Fortinet FortiOS, '
            'Palo Alto PAN-OS, and Huawei VRP.'
            '</font>',
            self.styles['BodyText2']
        ))
        return story

    def build(self):
        """Generate the PDF and return bytes"""
        doc = SimpleDocTemplate(
            self.buffer,
            pagesize=LETTER,
            leftMargin=0.6 * inch,
            rightMargin=0.6 * inch,
            topMargin=0.7 * inch,
            bottomMargin=0.7 * inch,
            title='SecureAudit Compliance Report',
            author='SecureAudit'
        )

        story = []
        story.extend(self._cover_page())
        story.extend(self._summary_section())
        story.extend(self._violations_section())
        story.extend(self._footer_section())

        doc.build(
            story,
            onFirstPage=self._draw_cover,
            onLaterPages=self._draw_header_footer
        )

        pdf_bytes = self.buffer.getvalue()
        self.buffer.close()
        return pdf_bytes